### PR TITLE
Use nfsexports for NFS export management

### PR DESCRIPTION
**Pull request by johanneswuerbach**
While working on https://github.com/zchee/docker-machine-driver-xhyve, I wrote a small util to manage NFS exports https://travis-ci.org/johanneswuerbach/nfsexports.

It supports:
- Verifying that the resulting exports is correct
- Correct line break merging
- Allows adding and removed with a unique id

Contributions definitely welcome. WDYT?

### CODE REVIEW

**Comment by AntonioMeireles** [comment]
@johanneswuerbach thanks!!!!!! this is going to be a definitive improvement!

fwiw, on a quick run, this doesn't seems to be fully working right now. (/etc/exports isn't updated in my side). will dig deeper (not sure if tomorrow or Thursday yet).

**Comment by johanneswuerbach** [comment]
Yep, I totally missed handling the returned error. Will add it tmrw.

**Comment by rimusz** [comment]
:+1:

**Comment by johanneswuerbach** [comment]
Error handling added.

**Comment by AntonioMeireles** [comment]
@johanneswuerbach 

your PR raised a few interesting questions and uncovered a few design quirks in my side. Point is, `corectl` _always_ expects one and just one, NFS share to be set up (`/Users` available to VM's network). No more, no less, regardless of the # of running VMs. OTOH, currently by design `corectl` is daemonless, so there's not a simple way to mount/unmount `/Users` _a la carte_ when there (may be) several VMs running. (one could probably cheat a bit and sort of dedupe the shares by restricting each one to the expected VM's IP, and not as today to the whole VM's network, but that would be overdesigning and prone to other issues)

So what i ended doing, in the meantime, was to refactor existing code a bit to better handle failures (and discerning between when NFSd is running already and when it is not) but keeping previous structure.

Finally, this doesn't mean i think that things are clean/nice enough that there's no way for improvement/better abstraction, which there is - and this is why i'm leaving this open, as i'd love your feedback. 

Happy New Year!

**Comment by johanneswuerbach** [comment]
Yep, I also discovered that corectl is using a single share for the whole vmnet range. Won't this break all other vmnet based VMs running in the same range requiring different NFS settings?

**Comment by AntonioMeireles** [comment]
@johanneswuerbach afaict it shouldn't. end-user can still set whatever NFS shares he wants. we are just enforcing that we expect one to be set up by default - /Users.

**Comment by johanneswuerbach** [comment]
Tested and verified that two shares in the same network are actually not conflicting:

```
/Users -network 192.168.64.0 -mask 255.255.255.0 -alldirs -mapall=501:20
/Users 192.168.64.44 -alldirs -maproot=root
```

I think even with one share this PR it is still valuable to have shared manage nfs exports implementation, also you current implementation has some issues around creating invalid `/etc/exports` and not reverting them (you run checkexports after already writing the file).

So rebased :-)

**Comment by AntonioMeireles** [comment]
@johanneswuerbach thanks! 

my main use-case where one actually gets conflicting shares (that i hope is catched and forces a gracefull fail on latest _tip_) would be when `corectl` gets called by different users in same machine (which would get us conflicting entries in `/etc/exports` (as the `-mapall` args would differ)). fwiw, i'm calling `checkexports` just to be sure (before attempting to boot VM) that we'll _just_ have working NFS, no more, no less. In no way i'm trying to catch all error combinatiosn that may arise other than the ones that may come _just_ from using `corectl`. 

btw, if i'm reading things correctly your `fsexports.ReloadDaemon()` assumes that `nfsd` is always running, which may or not be true. (i'm still looking at ways to get this nicer / smoother globally)

**Comment by johanneswuerbach** [comment]
With my (default) nfsd launch deamon config, nfsd is auto-started when you `touch /etc/exports`, so technically there is no checking required, but a good additional safety measure (will add).

With not catching I mean that you append the new share directly to `/etc/exports` then run `nfsd checkexports`. So in case your added share is breaking nfsd, the user will end up with a broken config and a stopped nfsd. (This can happen if you use e.g. vagrant which adds `/Users/user/subdir`, which breaks when you also add `/Users` :-()

I workaround that issue by copying everything to a tempfile and checking whether that file is correct before overwriting the actual config.
https://github.com/johanneswuerbach/nfsexports/blob/master/nfsexports.go#L104-L124

**Comment by AntonioMeireles** [comment]
Ah, you're still using `vagrant` and want to avoid collisions with it. (will hot fix the points you raised in the meantime)

~~(meanwhile trying to remember why i ended sharing `/Users` instead of `/Users/$username`)~~ it's so that `/Users/$username` mounts cleanly inside VM. @johanneswuerbach  are you aware of another way btw ?

**Comment by AntonioMeireles** [comment]
@johanneswuerbach i _think_ that _now_ (post 0.5.2) your way is _really_ doable without breaking `corectl` assumptions. my only issue now, at sight, is how to consume your lib without breaking migration from older `corectl` versions.

**Comment by AntonioMeireles** [comment]
closing as not apliable anymore.

**Pull request closed without merging**
